runmode: debug             # 开发模式， debug, release, test
addr: :8080                # HTTP 绑定端口
name: go-apiserver         # API server 的名字
url: http://127.0.0.1:8080 # pingServer 函数请求的API服务器的IP:PORT
max_ping_count: 10         # pingServer 函数 try 的次数